<?xml version="1.0"?>
<robot xmlns:xacro = "http:://www.ros.org/wiki/xacro" name="dtb_quadruped">

	<xacro:include filename="$(find dtb_quadruped_description)/robots/dtb_quadruped.gazebo.xacro"/>

	<!--Xacro Properties-->

	<xacro:property name="body_box_length" value="0.6"/>
	<xacro:property name="body_box_width" value="0.25"/>
	<xacro:property name="body_box_height" value="0.1"/>
	<xacro:property name="M_PI" value="3.1415926"/>

	<!-- Base Description-->

	<link name="base_footprint"/>
	
	<joint name="base_joint" type="fixed">
		<parent link="base_footprint"/>
		<child link="base_link"/>
		<origin xyz="0 0 0"/>
		<axis xyz="0 0 0"/>
	</joint>
	
	<link name="base_link">
		<visual>
			<origin xyz = "0 0 0" rpy = "0 0 0"/>
			<geometry>
				<box size = "${body_box_length} ${body_box_width} ${body_box_height}"/>
			</geometry>
			<material name = "body_color"/>
		</visual>
		<collision>
			<origin xyz = "0 0 0" rpy = "0 0 0"/>
			<geometry>
				<box size = "${body_box_length} ${body_box_width} ${body_box_height}"/>
			</geometry>
		</collision>
		<inertial>
			<origin xyz = "0 0 0" rpy = "0 0 0"/>
			<mass value = "2.0"/>
			<inertia
    	    	ixx="0.01201" ixy="0.0" ixz="0.0"
    	    	iyy="0.06167" iyz="0.0"
    	    	izz="0.07042"/>
		</inertial>
	</link>
	
	<!-- Turn Motor -->
	
	<xacro:macro name="t_motor_macro" params="t_motor_num x_pos y_pos">
		<link name="t_motor_${t_motor_num}">
			<visual>
				<origin xyz = "0 0 0" rpy = "0 0 0"/>
				<geometry>
					<cylinder length="0.03" radius="0.04"/>
				</geometry>
				<material name = "t_motor_color"/>
			</visual>
			<collision>
				<origin xyz = "0 0 0" rpy = "0 0 0"/>
				<geometry>
					<cylinder length="0.03" radius="0.04"/>
				</geometry>
			</collision>
			<inertial>
				<origin xyz = "0 0 0" rpy = "0 0 0"/>
				<mass value = "0.5"/>
				<inertia
    	    			ixx="0.0003" ixy="0.0" ixz="0.0"
    	    			iyy="0.0003" iyz="0.0"
    	    			izz="0.0004"/>
			</inertial>
		</link>
		<joint name="t_motor_${t_motor_num}_joint" type="revolute">
			<parent link="base_link"/>
			<child link="t_motor_${t_motor_num}"/>
			<origin xyz="${x_pos} ${((body_box_width/2)-0.03)*y_pos} ${(-body_box_height/2)+0.04}" rpy="0 ${M_PI/2} 0"/>
			<axis xyz="0 0 1"/>
			<limit effort="15" lower="${(-M_PI/10)*y_pos}" upper="${(M_PI/10)*y_pos}" velocity="157"/>
		</joint>
	</xacro:macro>
	<xacro:t_motor_macro t_motor_num="1" x_pos="${(body_box_length/2)-0.1}" y_pos="1"/>
	<xacro:t_motor_macro t_motor_num="2" x_pos="${(body_box_length/2)-0.1}" y_pos="-1"/>
	<xacro:t_motor_macro t_motor_num="3" x_pos="${-(body_box_length/2)+0.016}" y_pos="1"/>
	<xacro:t_motor_macro t_motor_num="4" x_pos="${-(body_box_length/2)+0.016}" y_pos="-1"/>
	
	<!-- Turn to Loco Motor Joint -->
	
	<xacro:macro name="t_l_link_macro" params="t_l_link_num">
		<link name="t_l_link_${t_l_link_num}">
			<visual>
				<origin xyz = "0 0 0" rpy = "0 0 0"/>
				<geometry>
					<cylinder length="0.08" radius="0.04"/>
				</geometry>
				<material name = "black"/>
			</visual>
			<collision>
				<origin xyz = "0 0 0" rpy = "0 0 0"/>
				<geometry>
					<cylinder length="0.08" radius="0.04"/>
				</geometry>
			</collision>
			<inertial>
				<origin xyz = "0 0 0" rpy = "0 0 0"/>
				<mass value = "0.3"/>
				<inertia
    	    			ixx="0.00028" ixy="0.0" ixz="0.0"
    	    			iyy="0.00028" iyz="0.0"
    	    			izz="0.00024"/>
			</inertial>
		</link>
		<joint name="t_l_link_${t_l_link_num}_joint" type="fixed">
			<parent link="t_motor_${t_l_link_num}"/>
			<child link="t_l_link_${t_l_link_num}"/>
			<origin xyz="0 0 0.055" rpy="0 0 0"/>
			<axis xyz="0 0 1"/>
		</joint>
	</xacro:macro>
	<xacro:t_l_link_macro t_l_link_num="1"/>
	<xacro:t_l_link_macro t_l_link_num="2"/>
	<xacro:t_l_link_macro t_l_link_num="3"/>
	<xacro:t_l_link_macro t_l_link_num="4"/>
	
	<!-- Loco Motor -->
	
	<xacro:macro name="l_motor_macro" params="l_motor_num pose">
		<link name="l_motor_${l_motor_num}">
			<visual>
				<origin xyz = "0 0 0" rpy = "0 0 0"/>
				<geometry>
					<cylinder length="0.03" radius="0.039"/>
				</geometry>
				<material name = "l_motor_color"/>
			</visual>
			<collision>
				<origin xyz = "0 0 0" rpy = "0 0 0"/>
				<geometry>
					<cylinder length="0.03" radius="0.039"/>
				</geometry>
			</collision>
			<inertial>
				<origin xyz = "0 0 0" rpy = "0 0 0"/>
				<mass value = "0.5"/>
				<inertia
    	    			ixx="0.0003" ixy="0.0" ixz="0.0"
    	    			iyy="0.0003" iyz="0.0"
    	    			izz="0.0004"/>
			</inertial>
		</link>
		<joint name="l_motor_${l_motor_num}_joint" type="revolute">
			<parent link="t_l_link_${l_motor_num}"/>
			<child link="l_motor_${l_motor_num}"/>
			<origin xyz="0 ${(0.055)*pose} 0" rpy="${(-M_PI/2)*pose} 0 0"/>
			<axis xyz="0 0 1"/>
			<limit effort="15" lower="${(-M_PI/2)+((-M_PI/2)*pose)}" upper="${(M_PI/2)-((M_PI/2)*pose)}" velocity="157"/>
		</joint>
	</xacro:macro>
	<xacro:l_motor_macro l_motor_num="1" pose="1"/>
	<xacro:l_motor_macro l_motor_num="2" pose="-1"/>
	<xacro:l_motor_macro l_motor_num="3" pose="1"/>
	<xacro:l_motor_macro l_motor_num="4" pose="-1"/>
	
	<!-- Thigh Link -->
	
	<xacro:macro name="thigh_link_macro" params="thigh_num pose">
		<link name="thigh_link_${thigh_num}">
			<visual>
				<origin xyz = "0 0 0" rpy = "0 0 0"/>
				<geometry>
					<box size="0.25 0.08 0.03"/>
				</geometry>
				<material name = "thigh_color"/>
			</visual>
			<collision>
				<origin xyz = "0 0 0" rpy = "0 0 0"/>
				<geometry>
					<box size="0.25 0.08 0.03"/>
				</geometry>
			</collision>
			<inertial>
				<origin xyz = "0 0 0" rpy = "0 0 0"/>
				<mass value = "0.3"/>
				<inertia
    	    			ixx="0.0001825" ixy="0.0" ixz="0.0"
    	    			iyy="0.001585" iyz="0.0"
    	    			izz="0.001722"/>
			</inertial>
		</link>
		<joint name="l_thigh_${thigh_num}_joint" type="fixed">
			<parent link="l_motor_${thigh_num}"/>
			<child link="thigh_link_${thigh_num}"/>
			<origin xyz="0 ${0.125*pose} 0.015" rpy="0 0 ${(M_PI/2)*pose}"/>
			<axis xyz="0 0 1"/>
		</joint>
	</xacro:macro>
	<xacro:thigh_link_macro thigh_num="1" pose="1"/>
	<xacro:thigh_link_macro thigh_num="2" pose="-1"/>
	<xacro:thigh_link_macro thigh_num="3" pose="1"/>
	<xacro:thigh_link_macro thigh_num="4" pose="-1"/>
	
	<xacro:macro name="thigh_semicirc_macro" params="thigh_num up_down">
		<link name="thigh_semicirc_${thigh_num}_${up_down}">
			<visual>
				<origin xyz = "0 0 0" rpy = "0 0 0"/>
				<geometry>
					<cylinder length="0.03" radius="0.04"/>
				</geometry>
				<material name = "thigh_color"/>
			</visual>
			<collision>
				<origin xyz = "0 0 0" rpy = "0 0 0"/>
				<geometry>
					<cylinder length="0.03" radius="0.04"/>
				</geometry>
			</collision>
			<inertial>
				<origin xyz = "0 0 0" rpy = "0 0 0"/>
				<mass value = "0.1"/>
				<inertia
    	    			ixx="0.0000475" ixy="0.0" ixz="0.0"
    	    			iyy="0.0000475" iyz="0.0"
    	    			izz="0.00008"/>
			</inertial>
		</link>
		<joint name="thigh_semicirc_${thigh_num}_${up_down}_joint" type="fixed">
			<parent link="thigh_link_${thigh_num}"/>
			<child link="thigh_semicirc_${thigh_num}_${up_down}"/>
			<origin xyz="${up_down*0.125} 0 0" rpy="0 0 0"/>
			<axis xyz="0 0 1"/>
		</joint>
	</xacro:macro>
	<xacro:thigh_semicirc_macro thigh_num="1" up_down="-1"/>
	<xacro:thigh_semicirc_macro thigh_num="1" up_down="1"/>
	<xacro:thigh_semicirc_macro thigh_num="2" up_down="-1"/>
	<xacro:thigh_semicirc_macro thigh_num="2" up_down="1"/>
	<xacro:thigh_semicirc_macro thigh_num="3" up_down="-1"/>
	<xacro:thigh_semicirc_macro thigh_num="3" up_down="1"/>
	<xacro:thigh_semicirc_macro thigh_num="4" up_down="-1"/>
	<xacro:thigh_semicirc_macro thigh_num="4" up_down="1"/>
	
	<!-- Height Motor -->
	
	<xacro:macro name="h_motor_macro" params="h_motor_num pose">
		<link name="h_motor_${h_motor_num}">
			<visual>
				<origin xyz = "0 0 0" rpy = "0 0 0"/>
				<geometry>
					<cylinder length="0.03" radius="0.041"/>
				</geometry>
				<material name = "h_motor_color"/>
			</visual>
			<collision>
				<origin xyz = "0 0 0" rpy = "0 0 0"/>
				<geometry>
					<cylinder length="0.03" radius="0.041"/>
				</geometry>
			</collision>
			<inertial>
				<origin xyz = "0 0 0" rpy = "0 0 0"/>
				<mass value = "0.5"/>
				<inertia
    	    			ixx="0.0003" ixy="0.0" ixz="0.0"
    	    			iyy="0.0003" iyz="0.0"
    	    			izz="0.0004"/>
			</inertial>
		</link>
		<joint name="h_motor_${h_motor_num}_joint" type="revolute">
			<parent link="thigh_link_${h_motor_num}"/>
			<child link="h_motor_${h_motor_num}"/>
			<origin xyz="0.125 0 0.015" rpy="0 0 0"/>
			<axis xyz="0 0 1"/>
			<limit effort="15" lower="${0 + (-M_PI*pose)}" upper="${M_PI-(pose*M_PI)}" velocity="157"/>
		</joint>
	</xacro:macro>
	<xacro:h_motor_macro h_motor_num="1" pose="0"/>
	<xacro:h_motor_macro h_motor_num="2" pose="1"/>
	<xacro:h_motor_macro h_motor_num="3" pose="0"/>
	<xacro:h_motor_macro h_motor_num="4" pose="1"/>
	
	<!-- Calf Link -->
	
	<xacro:macro name="calf_link_macro" params="calf_num">
		<link name="calf_link_${calf_num}">
			<visual>
				<origin xyz = "0 0 0" rpy = "0 0 0"/>
				<geometry>
					<box size="0.25 0.06 0.03"/>
				</geometry>
				<material name = "calf_color"/>
			</visual>
			<collision>
				<origin xyz = "0 0 0" rpy = "0 0 0"/>
				<geometry>
					<box size="0.25 0.06 0.03"/>
				</geometry>
			</collision>
			<inertial>
				<origin xyz = "0 0 0" rpy = "0 0 0"/>
				<mass value = "0.3"/>
				<inertia
    	    			ixx="0.0001825" ixy="0.0" ixz="0.0"
    	    			iyy="0.001585" iyz="0.0"
    	    			izz="0.001722"/>
			</inertial>
		</link>
		<joint name="h_calf_${calf_num}_joint" type="fixed">
			<parent link="h_motor_${calf_num}"/>
			<child link="calf_link_${calf_num}"/>
			<origin xyz="-0.125 0 0.015" rpy="0 0 0"/>
			<axis xyz="0 0 1"/>
		</joint>
	</xacro:macro>
	<xacro:calf_link_macro calf_num="1"/>
	<xacro:calf_link_macro calf_num="2"/>
	<xacro:calf_link_macro calf_num="3"/>
	<xacro:calf_link_macro calf_num="4"/>
	
	<xacro:macro name="calf_semicirc_macro" params="calf_num up_down">
		<link name="calf_semicirc_${calf_num}_${up_down}">
			<visual>
				<origin xyz = "0 0 0" rpy = "0 0 0"/>
				<geometry>
					<cylinder length="0.03" radius="0.03"/>
				</geometry>
				<material name = "calf_color"/>
			</visual>
			<collision>
				<origin xyz = "0 0 0" rpy = "0 0 0"/>
				<geometry>
					<cylinder length="0.03" radius="0.03"/>
				</geometry>
			</collision>
			<inertial>
				<origin xyz = "0 0 0" rpy = "0 0 0"/>
				<mass value = "0.1"/>
				<inertia
    	    			ixx="0.0000475" ixy="0.0" ixz="0.0"
    	    			iyy="0.0000475" iyz="0.0"
    	    			izz="0.00008"/>
			</inertial>
		</link>
		<joint name="calf_semicirc_${calf_num}_${up_down}_joint" type="fixed">
			<parent link="calf_link_${calf_num}"/>
			<child link="calf_semicirc_${calf_num}_${up_down}"/>
			<origin xyz="${up_down*0.125} 0 0" rpy="0 0 0"/>
			<axis xyz="0 0 1"/>
		</joint>
	</xacro:macro>
	<xacro:calf_semicirc_macro calf_num="1" up_down="-1"/>
	<xacro:calf_semicirc_macro calf_num="1" up_down="1"/>
	<xacro:calf_semicirc_macro calf_num="2" up_down="-1"/>
	<xacro:calf_semicirc_macro calf_num="2" up_down="1"/>
	<xacro:calf_semicirc_macro calf_num="3" up_down="-1"/>
	<xacro:calf_semicirc_macro calf_num="3" up_down="1"/>
	<xacro:calf_semicirc_macro calf_num="4" up_down="-1"/>
	<xacro:calf_semicirc_macro calf_num="4" up_down="1"/>
	
	<!-- Rviz Colors -->

	<material name = "body_color">
		<color rgba="1 1 1 1"/>
	</material>
	<material name = "black">
		<color rgba="0 0 0 1"/>
	</material>
	<material name = "t_motor_color">
		<color rgba="1 1 0 1"/>
	</material>
	<material name = "l_motor_color">
		<color rgba="1 1 0 1"/>
	</material>
	<material name = "h_motor_color">
		<color rgba="1 0 0 1"/>
	</material>
	<material name = "thigh_color">
		<color rgba="1 1 1 1"/>
	</material>
	<material name = "calf_color">
		<color rgba="0 0 0 1"/>
	</material>


</robot>
